#=================================================
# https://github.com/danxiaonuo/dns-docker
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动编译并上传镜像

# 设置触发条件
on:
  # 仓库触发工作流
  repository_dispatch:
  # 编辑文件触发开始编译
  push:
    paths:
      - 'Dockerfile'
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build dns'
        required: true
        default: 'build dns'
  # 定时触发编译(每天早5点)
  schedule:
     - cron: '0 21 * * *'
  # 点☆Star触发开始编译
  watch:  
     types: [started]

# 权限
permissions:
  contents: write
  actions: write
  
# 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest
    
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出各个模块代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 安装 QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: 安装 docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: 登录 DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: 构建镜像并发布
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dns:${{ matrix.DOCKER_TAG }}
      
    - name: 删除旧的GitHub-workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
